version: "3.8"

services:
  karty-app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - karty-db
      - karty-cache
    environment:
      DB_HOST: karty-db
      DB_PORT: 3306
      DB_NAME: karty
      DB_USER: root
      DB_PASSWORD: root
      CACHE_HOST: karty-cache
      CACHE_PORT: 6379
      BUCKET_SIZE: 1
      BUCKET_REFILL_DURATION: 60
      AUTH_TOKEN_EXPIRY: 1800
    ports:
      - 8080:8080
  karty-db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: karty
    ports:
      - 3306:3306
    # (this is just an example, not intended to be a production configuration)
  karty-cache:
    image: redis/redis-stack-server:latest
    ports:
      - 6379:6379
